name: nba_transformations

profile: nba_transformations

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  nba_transformations:
    +schema: raw

models:
  nba_transformations:
    staging:
      +materialized: view
    marts:
      +materialized: table
